# Generated by Django 2.2.5 on 2019-09-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
