# Generated by Django 2.2.5 on 2019-09-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
